server:
  port: 443

  ssl:
    enabled: true
    key-store: /home/ubuntu/keystore.p12
    key-store-type: PKCS12
    key-alias: tomcat
    key-store-password: ${ssl.prod.password}

  tomcat:
    mbean-registry:
      enabled: true

spring:
  config:
    import:
      - security/db.yml
      - security/ssl.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.prod.host}:${db.prod.port}/${db.prod.name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db.prod.username}
    password: ${db.prod.password}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop

  cloud:
    aws:
      region:
        static: ap-northeast-2

jwt:
  secret-key: s8R$kQz3nZ!L5pT7c@J#xM9vB1&uD6hE

kasi:
  base-url: https://apis.data.go.kr/B090041/openapi
  secret-key: 2yUyrqooUJ111Di09rkgSJZcuDe6zeexdXax1oQM1pKnRu1B3GmjpoeUIzYzgwPYLA0SUDhoYSaFRAo9/Go6dw==
  connect-timeout: 3000
  read-timeout: 5000

logging:
  level:
    org:
      hibernate:
        SQL: debug

management:
  metrics:
    enable:
      system.cpu.usage: true
      jvm.memory.used: true
      jvm.memory.max: true
      http.server.requests: true
      tomcat.threads: true
      app.health.status: true
      hikaricp.connections.active: true
      hikaricp.connections.pending: true
      hikaricp.connections.max: true
      hikaricp.connections.timeout: true
      logback.events: true
  cloudwatch:
    metrics:
      export:
        enabled: true
        step: 1m
        namespace: EC2/lv3-Murphy-api
